fix (crash) : crash when send vibrated notification
java.lang.RuntimeException: Unable to start receiver rikka.searchbyimage.receiver.UploadMessageReceiver: java.lang.SecurityException: Requires VIBRATE permission