fix (crash) : error in inflating WebView
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
Error inflating class android.webkit.WebView